### ISSUE TITLE
Bump gulp to fix Node v10 error

### ISSUE THREAD

**Issue by pratheekrebala** [PublicI/app-generator#14]
https://github.com/gulpjs/gulp/issues/2162

This prevents being able to do `gulp push` from a Node v10 client.

**Comment by chriszs** [comment]
Just did this. We may want to consider ditching gulp. It's semi-vestigial from when I tried to maintain my own Webpack/asset/Babel build chain. The template mainly uses it for pushing to S3. It's still decent at that, but it's a heavy dep.
