### ISSUE TITLE
s3-deploy breaks video files

### ISSUE THREAD

**Issue by pratheekrebala** [PublicI/app-generator#26]
I've had to re-upload the video files using `aws s3` CLI or the s3 GUI multiple times. It also over-writes the files on subsequent pushes even if the video file hasn't changed.

I have a feeling this has to do with the `--gzip` flag that is included with the `yarn push` command.

**Comment by chriszs** [comment]
I had the same experience and uploaded mine using Cyberduck. Connected to #22.

**Comment by chriszs** [comment]
Totally legit to swap s3-deploy out on a per-project basis, could form the basis of a PR.

**Comment by chriszs** [comment]
See #22.
